AWSTemplateFormatVersion: 2010-09-09
Mappings:
  SubnetConfig:
    VPC:
      CIDR: 10.0.0.0/16
    SubnetPub1:
      CIDR: 10.0.0.0/19
    SubnetPub2:
      CIDR: 10.0.32.0/19
    SubnetPrv1:
      CIDR: 10.0.64.0/19
    SubnetPrv2:
      CIDR: 10.0.96.0/19
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  SubnetPub1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      VpcId: !Ref VPC
      CidrBlock: !FindInMap ['SubnetConfig', 'SubnetPub1', 'CIDR']
      MapPublicIpOnLaunch: true
  SubnetPub2:
    Type: AWS::EC2::Subnet
    Properties:
        AvailabilityZone: !Select [1, !GetAZs ]
        VpcId: !Ref VPC
        CidrBlock: !FindInMap ['SubnetConfig', 'SubnetPub2', 'CIDR']
        MapPublicIpOnLaunch: true
  SubnetPrv1:
    Type: AWS::EC2::Subnet
    Properties:
        AvailabilityZone: !Select [2, !GetAZs ]
        VpcId: !Ref VPC
        CidrBlock: !FindInMap ['SubnetConfig', 'SubnetPrv1', 'CIDR']
  SubnetPrv2:
    Type: AWS::EC2::Subnet
    Properties:
        AvailabilityZone: !Select [3, !GetAZs ]
        VpcId: !Ref VPC
        CidrBlock: !FindInMap ['SubnetConfig', 'SubnetPrv2', 'CIDR']
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
         VpcId: !Ref VPC
         InternetGatewayId: !Ref MyInternetGateway
  MyPubRouteTable:
     Type: AWS::EC2::RouteTable
     Properties:
       VpcId: !Ref VPC
  PublicRoute:   # Public route table has direct routing to IGW:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref MyPubRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway
  Pub1RouteTableAssociation:
     Type: AWS::EC2::SubnetRouteTableAssociation
     Properties:
       SubnetId: !Ref SubnetPub1
       RouteTableId: !Ref MyPubRouteTable
  Pub2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
       SubnetId: !Ref SubnetPub2
       RouteTableId: !Ref MyPubRouteTable
  NatGatewayOne:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayOneAttachment.AllocationId
      SubnetId: !Ref SubnetPub1
  NatGatewayTwo:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayTwoAttachment.AllocationId
      SubnetId: !Ref SubnetPub2
  NatGatewayOneAttachment:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
        Domain: vpc
  NatGatewayTwoAttachment:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
        Domain: vpc
  PrivateRouteTable1:
     Type: AWS::EC2::RouteTable
     Properties:
       VpcId: !Ref VPC
  PrivateRoute1:
     Type: AWS::EC2::Route
     Properties:
       RouteTableId: !Ref PrivateRouteTable1
       DestinationCidrBlock: 0.0.0.0/0
       NatGatewayId: !Ref NatGatewayOne
  PrivateRouteTable1Association:
     Type: AWS::EC2::SubnetRouteTableAssociation
     Properties:
       RouteTableId: !Ref PrivateRouteTable1
       SubnetId: !Ref SubnetPrv1
  PrivateRouteTable2:
     Type: AWS::EC2::RouteTable
     Properties:
       VpcId: !Ref VPC
  PrivateRoute2:
     Type: AWS::EC2::Route
     Properties:
       RouteTableId: !Ref PrivateRouteTable2
       DestinationCidrBlock: 0.0.0.0/0
       NatGatewayId: !Ref NatGatewayTwo
  PrivateRouteTable2Association:
     Type: AWS::EC2::SubnetRouteTableAssociation
     Properties:
       RouteTableId: !Ref PrivateRouteTable2
       SubnetId: !Ref SubnetPrv2
Outputs:
  vpcid:
    Description: ID of Infrastructure VPC
    Value: !Ref VPC
  SubnetPub1Info:
    Description: ID of the Subnets
    Value: !Ref SubnetPub1
  SubnetPub2Info:
     Description: ID of the Subnets
     Value: !Ref SubnetPub2
  SubnetPrv1Info:
    Description: ID of the Subnets
    Value: !Ref SubnetPrv1
  SubnetPrv2Info:
    Description: ID of the Subnets
    Value: !Ref SubnetPrv2