AWSTemplateFormatVersion: 2010-09-09
Description: AWPRMIPS-1ASB-Apps01 - 10.140.22.0/24
Mappings:
  #VPCId:
  #SubnetId:
  #KeyPairId: 
  #SecurityGroupIds:
    #AWPRMIPS-SG-ACS_FUSE: 
    #AWPRMIPS-SG-ACS_EDV:
    #AWPRMIPS-SG-RMS:
    #AWPRMIPS-SG-EDW_TERRADATA:
    #AWPRMIPS-SG-ACS_OPENSHIFT:
    #AWPRMIPS-SG-CACHE:
    #AWPRMIPS-SG-EDW_TALEND:
    #AWPRMIPS-SG-ACS_MDACA:
    #AWPRMIPS-SG-EDW_EMR:
    #AWPRMIPS-SG-ODS_POSTGRES:
    #AWPRMIPS-SG-EDW_SQLFARM:
    #AWPRDHAE-SG-COR-CISCOCSR-G2:
  #AMIIds:
    #Windows2016:
    #Windows2012:
    #Linux:
  
Resources:  
  FILL_INSTANCE_NAME:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: true
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 200
            VolumeType: gp2
            DeleteOnTermination: true
        -
          DeviceName: "/dev/sdc"
          Ebs:
            VolumeSize: 200
            VolumeType: gp2
            DeleteOnTermination: false
        -
          DeviceName: "/dev/sdd"
          Ebs:
            VolumeSize: 200
            VolumeType: gp2
            DeleteOnTermination: false
      InstanceType: t2.nano
      ImageId: !FindInMap ['AMIIds', 'Windows']
      KeyName: !Ref KeyPairId
      SecurityGroupIds: !FindInMap ['SecurityGroupIds', 'FILL_SECURITY_GROUP_NAME']
      SubnetId: !Ref SubnetId
      Tags: 
        - 
          Key: "Solution"
          Value: "value"
        - 
          Key: "Name"
          Value: "value"
        - 
          Key: "Enviroment"
          Value: "Prod"