---
Resources:
 EC2Instance:
   Type: AWS::EC2::Instance
   Properties:
    ImageId: ami-062f7200baf2fa504
    InstanceType: t2.micro
    SubnetId: subnet-092963a562e894d2a
    SecurityGroupIds: sg-07b5de53e02eb83dc
    KeyName: HIIDEV

 MyEIP:
   Type: AWS::EC2::EIP
   Properties:
    InstanceId: !Ref 
